apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment
  namespace: user-portal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      containers:
      - name: backend-container
        image: sidpram/user-dashboard-backend:latest

        ports:
        - containerPort: 3000
        
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 6
          periodSeconds: 10

        env:
        - name: PORT
          #value: "3000"
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: PORT

        - name: MONGO_URI
          #value: mongodb://mongodb:27017/user_portal
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MONGO_URI
