apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment
  namespace: user-portal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend-container
        image: sidpram/user-dashboard-backend:v2

        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"

        - name: MONGO_URI
          value: mongodb://mongodb:27017/user_portal
