version: '3.8'

services:
  # -----------------------------------------------
  # 1. DATABASE TIER (Official MongoDB Image)
  # -----------------------------------------------
  mongodb:
    image: mongo:6.0
    container_name: dashboard_db
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - mynet



  # -----------------------------------------------
  # 2. BACKEND API TIER (Custom Multi-Stage Node.js)
  # -----------------------------------------------
  backend:
    build: ./backend
    container_name: dashboard_backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy # <--- Waits for Mongo db ping
    networks:
      - mynet


  # -----------------------------------------------
  # 3. FRONTEND UI TIER
  # -----------------------------------------------
  frontend:
    build: ./frontend
    container_name: dashboard_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:

volumes:
  mongo_data: